version: "3.7"

services:
  mona_makeup:
    build: .
    ports:
      - "5000:5000"
    container_name: mona_makeup
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - bpnet
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - bpnet


  mysql: 
    image: mysql
    container_name: mysql
    
    environment:
      - MYSQL_DATABASE=mona_makeup
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_USER=mona_makeup
      - MYSQL_PASSWORD=lozinka
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - bpnet
    


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
   
    networks:
      - bpnet
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     
    networks:
      - bpnet

volumes:
  mysql:
networks:
  bpnet:
    driver: bridge
